build_mode = "release"
target_adapters = [
    "noir",
    "circom",
    "halo2",
]
target_platforms = ["android", "ios"]
android = ["aarch64-linux-android"]
ios = ["aarch64-apple-ios", "aarch64-apple-ios-sim"]
auto_update = false

[update]
